name: mentorship_EPAM
channels:
  - conda-forge
  - defaults
dependencies:
  - boruta_py=0.3
  - category_encoders=2.5.1.post0
  - click=7.1.2
  - cmdstanpy=1.0.4
  - cython=0.29.23
  - ipykernel=6.19.2
  - ipython=8.7.0
  - ipywidgets=7.6.3
  - jinja2=3.1.2
  - joblib=1.1.1
  - jupyter=1.0.0
  - jupyter_client=7.4.8
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_nbextensions_configurator=0.4.1
  - lightgbm=3.3.2
  - matplotlib=3.6.2
  - mlflow
  - nbconvert=6.5.4
  - nltk=3.7
  - notebook=6.5.2
  - numba=0.56.4
  - numpy=1.23.5
  - optuna=2.10.0
  - pandas=1.5.2
  - pip=22.3.1
  - plotly=5.9.0
  - pytest=6.2.3
  - python=3.8.15
  - requests=2.25.1
  - scikit-learn=1.1.3
  - scikit-optimize=0.9.0
  - scikit-plot
  - scipy=1.9.3
  - seaborn=0.12.2
  - shap=0.41.0
  - tqdm=4.59.0
  - pip:
    - pdpipe==0.3.0
    - prophet==1.1
    - skforecast==0.5.1