name: mentorship_EPAM
channels:
  - conda-forge
  - defaults
dependencies:
  - boruta_py=0.3
  - category_encoders=2.5.1.post0
  - click=7.1.2
  - cmdstanpy=1.0.4
  - cython=0.29.23
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipywidgets=7.6.3
  - jinja2=2.11.3
  - joblib=1.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_nbextensions_configurator=0.4.1
  - lightgbm=3.3.2
  - matplotlib=3.3.4
  - nbconvert=5.6.1
  - nltk=3.7
  - notebook=6.3.0
  - numba=0.53.1
  - numpy=1.22.4
  - optuna=2.10.0
  - pandas=1.2.4
  - pip=21.0.1
  - plotly=5.9.0
  - pytest=6.2.3
  - python=3.8.8
  - requests=2.25.1
  - scikit-learn=1.1.2
  - scikit-optimize=0.9.0
  - scipy=1.7.2
  - seaborn=0.11.2
  - shap=0.41.0
  - tqdm=4.59.0
  - pip:
    - pdpipe==0.3.0
    - prophet==1.1
    - skforecast==0.5.1